title: 망한 땅으로
description: 본격 개짬통 OSR
theme: just-the-docs/just-the-docs

url: https://bipedalocto.github.io/ITTa

aux_links:
  Repository: https://github.com/bipedalocto/ITTa

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Just the Docs configuration
just_the_docs:
  collections:
    # Define collections for any other content you'd like organized
    playermanual:
      name: Player Manual
      nav_order: 2
    background:
      name: Background
      nav_order: 3

# Enable or disable the site search
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2

# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

# Set the search token separator
# Default: /[\s\-/]+/
# Example: enable support for hyphenated search words
search.tokenizer_separator: /[\s\-/.,:;!?~()[\]'"]+/

# Display the relative url in search results
# Supports true (default) or false
search.rel_url: false

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true
